spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/interview-master;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: rg.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update