spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/interview-master
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: rg.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update