name: CI/CD

on:
  push:
    branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest # 실행 환경 지정

      # 실행 스텝 지정
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: '17'

        # application.yml 파일 설정
        - name: Setup application yml file
          run: |
            echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        # test 제외하고 build 진행
        - name: Build with Gradle
          run: ./gradlew clean build -x test

        # 빌드해서 생긴 JAR 파일을 깃허브 아티팩트로 업로드!!
        - name: Upload build artifact
          uses: actions/upload-artifact@v2
          with:
            name: interview
            path: build/libs/interview-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 현재 시간 가져오기-오디에 쓰는거야
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: interview
          path: build/libs/
      - name: NCP Deploy
        env:
          NCP_SSH_PRIVATE_KEY: ${{ secrets.NCP_SSH_PRIVATE_KEY }}
          NCP_HOST: ${{ secrets.NCP_HOST }}
          NCP_USER: ${{ secrets.NCP_USER }}

        run: |
          # SSH Key 파일 생성
          echo "$NCP_SSH_PRIVATE_KEY" > ncp_ssh_key
          chmod 600 ncp_ssh_key
          
          # 패키지 파일을 EC2 인스턴스로 복사
          scp -i ncp_ssh_key -o StrictHostKeyChecking=no build/libs/interview-0.0.1-SNAPSHOT.jar ${NCP_USER}@${NCP_HOST}:/home/${NCP_USER}/interview-server
          
          # 인스턴스에서 JAR 파일 실행
          ssh -i ncp_ssh_key -o StrictHostKeyChecking=no ${NCP_USER}@${NCP_HOST} "pgrep java | xargs kill -9; nohup java -jar /home/${NCP_USER}/interview-server/interview-0.0.1-SNAPSHOT.jar > /home/${NCP_USER}/interview-server/log/app.log 2>&1 &"